all: reader

reader:
	g++ -std=c++11 -Wall -Wextra reader_pref.cpp -o a.out -lpthread
	./a.out
writer:
	g++ -std=c++11 -Wall -Wextra write_pref.cpp -o a.out -lpthread
	./a.out
clean:
	/bin/rm -rf *.o 
